[package]
name = "monolith-finder"
version = "0.1.0"
authors = ["kahomayo <kahomayo@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
