
name: Automatic Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'v0.12.1'
    - name: Build
      run: cargo build --verbose
    - name: Build WASM
      run: wasm-pack build --dev
      working-directory: monolith-renderer
    - name: Run tests
      run: cargo test --verbose
