name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'v0.12.1'
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'
    - name: Build Rust
      run: wasm-pack build --release
      working-directory: monolith-renderer
    - run: npm install
      working-directory: monolith-renderer/www
    - name: Webpack
      run: npm run build
      working-directory: monolith-renderer/www
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: monolith-renderer/www/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
