name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'v0.9.1'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build Rust
      run: wasm-pack build --dev
      working-directory: monolith-renderer
    - run: npm install
      working-directory: monolith-renderer/www
    - name: Webpack
      run: npm run build
      working-directory: monolith-renderer/www
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target-branch: gh-pages
        build-dir: monolith-renderer/www/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
